### ISSUE TITLE
PHP error on a missing image

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#102]
If a product has an image defined, but that image is missing, it creates a php error:
[02-May-2018 11:53:49 Europe/Madrid] PHP Warning:  imagecreatefromjpeg(blah-blah/images/rg-general/rg-amk0001bk.jpg): failed to open stream: No such file or directory in blah-blah\includes\classes\bmz_image_handler.class.php on line 745
A cursory look at the class makes me think such a fundamental error should be caught earlier in the process, rather than fixing this line.

**Comment by lat9** [comment]
What Image Handler version?  Does the log have an associated backtrace?  Was this error generated on the storefront or admin-side?

**Comment by torvista** [comment]
Using this GIthub fileset, storefront.
Just rename an image file and look at that product on the storefront to generate the error.
I'm using Colorbox but I don't think that is relevant.

Full log:

> [02-May-2018 12:21:25 Europe/Madrid] Request URI: /tienda/manufacturers/rg-racing/general-accessories/rg-amk0001bk-mounting-kit-for-honda-averto-alarm-honda-cbr1000rr-2008-2011, IP address: 127.0.0.1
> #1  imagecreatefromjpeg() called at [LOCAL\public_html\tienda\includes\classes\bmz_image_handler.class.php:745]
> #2  ih_image->load_imageGD() called at [LOCAL\public_html\tienda\includes\classes\bmz_image_handler.class.php:546]
> #3  ih_image->resize_imageGD() called at [LOCAL\public_html\tienda\includes\classes\bmz_image_handler.class.php:340]
> #4  ih_image->get_resized_image() called at [LOCAL\public_html\tienda\includes\classes\bmz_image_handler.class.php:242]
> #5  ih_image->get_local() called at [LOCAL\public_html\tienda\includes\functions\extra_functions\functions_bmz_image_handler.php:105]
> #6  handle_image() called at [LOCAL\public_html\tienda\includes\functions\extra_functions\zen_colorbox.php:31]
> #7  zen_colorbox() called at [LOCAL\public_html\tienda\includes\templates\motorvista5\templates\tpl_modules_main_product_image.php:24]
> #8  require(LOCAL\public_html\tienda\includes\templates\motorvista5\templates\tpl_modules_main_product_image.php) called at [LOCAL\public_html\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php:66]
> #9  require(LOCAL\public_html\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php) called at [LOCAL\public_html\tienda\includes\modules\pages\product_info\main_template_vars.php:179]
> #10 require(LOCAL\public_html\tienda\includes\modules\pages\product_info\main_template_vars.php) called at [LOCAL\public_html\tienda\includes\templates\motorvista5\common\tpl_main_page.php:172]
> #11 require(LOCAL\public_html\tienda\includes\templates\motorvista5\common\tpl_main_page.php) called at [LOCAL\public_html\tienda\index.php:97]
> [02-May-2018 12:21:25 Europe/Madrid] PHP Warning:  imagecreatefromjpeg(D:/Documents/Business/Motorvista website/home-mvista/public_html/tienda/images/rg-general/rg-amk0001bk.jpg): failed to open stream: No such file or directory in LOCAL\public_html\tienda\includes\classes\bmz_image_handler.class.php on line 745
> 
>

**Comment by torvista** [comment]
While you are at it, I note also that the modules/YOUR_TEMPLATE files are not identical to the 1.55f versions in the unmodified sections, hindering comparisons a bit.

**Comment by lat9** [comment]
Please note (see #104) that the modules/YOUR_TEMPLATE files are now at a 1.5.6 level (no change comments).

**Comment by lat9** [comment]
One additional question:  What version of ColorBox are you using?

**Comment by lat9** [comment]
I'm unable to reproduce this issue using the 5.0.1-beta6 code.  I've cleared the bmz_cache directory and renamed the `images/microsoft/imexplorer.gif` so that it's not found.  No warnings are generated and the display shows no image.

**Comment by torvista** [comment]
1) I copied an image - to make it unique/never cached.
2) admin->product admin->browsed to that image to select and upload it.
3) deleted image (before viewing product catalog-side).
4) viewed product catalog side->debug created.

> 5.0.1-beta6 code
Is that this current code .zip?

**Comment by lat9** [comment]
I just created a 5.0.1-beta6 release (so we've got a stable/known set of code).

**Comment by torvista** [comment]
Tried that.
Major code changes noted from what I had...but issue remains.

> 
[21-May-2018 10:14:47 Europe/Madrid] Request URI: /tienda/index.php?main_page=product_info&cpath=1_12_50_1691&products_id=1705, IP address: 127.0.0.1
#1  imagecreatefromgif() called at [...\public_html\tienda\includes\classes\bmz_image_handler.class.php:804]
#2  ih_image->load_imageGD() called at [...\public_html\tienda\includes\classes\bmz_image_handler.class.php:618]
#3  ih_image->resize_imageGD() called at [...\public_html\tienda\includes\classes\bmz_image_handler.class.php:363]
#4  ih_image->get_resized_image() called at [...\public_html\tienda\includes\classes\bmz_image_handler.class.php:253]
#5  ih_image->get_local() called at [...\public_html\tienda\includes\functions\extra_functions\functions_bmz_image_handler.php:109]
#6  handle_image() called at [...\public_html\tienda\includes\functions\extra_functions\zen_colorbox.php:31]
#7  zen_colorbox() called at [...\public_html\tienda\includes\templates\motorvista5\templates\tpl_modules_main_product_image.php:24]
#8  require(...\public_html\tienda\includes\templates\motorvista5\templates\tpl_modules_main_product_image.php) called at [...\public_html\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php:66]
#9  require(...\public_html\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php) called at [...\public_html\tienda\includes\modules\pages\product_info\main_template_vars.php:179]
#10 require(...\public_html\tienda\includes\modules\pages\product_info\main_template_vars.php) called at [...\public_html\tienda\includes\templates\motorvista5\common\tpl_main_page.php:172]
#11 require(...\public_html\tienda\includes\templates\motorvista5\common\tpl_main_page.php) called at [...\public_html\tienda\index.php:97]
[21-May-2018 10:14:47 Europe/Madrid] PHP Warning:  imagecreatefromgif(.../public_html/tienda/images/ventureshield/vs-bpdu0004f - Copy.gif): failed to open stream: No such file or directory in ...\public_html\tienda\includes\classes\bmz_image_handler.class.php on line 804
----------------------------------

I note code modifications from vanilla are not commented as such in template override files.
I'll contact you privately for test site access.

Aside, this "bug" is a useful feature...tells me when images are missing!

**Comment by lat9** [comment]
Thanks for the link.

The template-override files are the same as the current v1.5.6 alpha; that's why no change-sections in those template-override modules!

**Comment by lat9** [comment]
Steve, I think I might see the problem.  If you edit /includes/auto_loaders/config.image_handler.php and change the auto-load "point" from 200 to 199 does the issue resolve?

**Comment by torvista** [comment]
why does additional_images/main_product_image IH5 have
`$GLOBALS['zco_notifier']`
instead of ZC155f
`$zco_notifier`

**Comment by lat9** [comment]
Because there are some plugins that include the module(s) in function-context, so the `zco_notifier` needs to be globalized for proper operation, i.e. no PHP errors.

**Comment by lat9** [comment]
I can confirm that the issue is due to the IH/ColorBox integration (no log generated when ColorBox is disabled).  I'll continue investigating tomorrow to determine where the source of the issue resides.

**Comment by lat9** [comment]
Where did ColorBox v2.1.3 come from?  The most recent posting on the Zen Cart Plugins is 2.1.2.

**Comment by lat9** [comment]
I'll note that I'm unable to reproduce this issue running v2.1.2 of ColorBox with IH-5.1-beta1 on zc156-alpha with the responsive classic template (PHP 7.1.4).

**Comment by lat9** [comment]
Finally (!).  The distinction is that your site has watermarking enabled, which is causing IH to (incorrectly) go down that image-generation path.

I'll note, also, that the `LARGE_IMAGE_WIDTH` and `LARGE_IMAGE_HEIGHT` settings used by ColorBox are undefined.

**Comment by lat9** [comment]
P.S. I've updated the file /includes/classes/bmz_image_handler_class.php on your test site.

**Comment by torvista** [comment]
Congratulations!
Sounds like that was a dog to get to the bottom of....which is an unfortunate use of english.
So now you have fixed that unrequested feature, it would be nice to get debug logs by design when it can't find a defined image! ha ha!!

**Comment by lat9** [comment]
Smarty-pants!  That's where the `/includes/extra_datafiles/image_handler_logging.php` file comes in.  It's currently not working for the admin (to-be-corrected real-soon-now), but for the storefront, just edit that file to indicate that you want storefront "logging" and you'll see some /logs/ih-debug*.log files being generated (one per page-load).

That's what I used to determine where this issue's source was.
