### ISSUE TITLE
Does not work with Zen Cart v155

### ISSUE THREAD

**Issue by prescottcomputing** [DivaVocals/zen_Image-Handler#134]
[16-Jun-2018 14:12:23 America/Phoenix] PHP Fatal error:  1064:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY pd.products_name' at line 6 :: SELECT ptc.* from products_to_categories ptc 
                LEFT JOIN products_description pd 
                    ON ptc.products_id = pd.products_id 
                   AND pd.language_id = 1 
              WHERE ptc.categories_id =  
           ORDER BY pd.products_name ==> (as called by) includes/ih_manager.php on line 54 <== in /includes/classes/db/mysql/query_factory.php on line 171

**Comment by lat9** [comment]
Could you describe what you were doing when that error occurred?

**Comment by prescottcomputing** [comment]
New install. No other modules installed. Logged in as Superuser. Installed module. 
In Admin, select Tools, then select Image Handler 5. Throws error that shows up in log.
WARNING: An Error occurred, please refresh the page and try again.
(You are presently using: v1.5.5f)

**Comment by lat9** [comment]
Interesting; I've been testing on zc1.5.6 and there are apparently (!) some differences.

You can change /admin/includes/ih_manager.php, line 54, to
        $new_product_query = $db->Execute(
            "SELECT ptc.* from " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc 
                LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd 
                    ON ptc.products_id = pd.products_id 
                   AND pd.language_id = " . (int)$_SESSION['languages_id'] . " 
              WHERE ptc.categories_id = " .  **(int)**$current_category_id . " 
           ORDER BY pd.products_name"
        );

to correct the issue.

**Comment by prescottcomputing** [comment]
Ok that fixed it. In retrospect I can see that the corrected query was already there in the same if statement!

Thanks!
