### ISSUE TITLE
zc156: previous/next product links overlap

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#153]
... due to changes in the `/includes/modules/products_prev_next_display.php` processing.  See #151 for additional details.

**Comment by lat9** [comment]
Just needed to add an HTML class to the table that "holds" the previous/next buttons.

**Comment by Pan2020** [comment]
I see, so that's what happened when there is no class to hold stuffs in place!

Now, the appearance is in order!
https://i.imgur.com/RVqTZJg.png

**Comment by lat9** [comment]
Thanks for the verification that the issue's resolved by that change!
