### ISSUE TITLE
Auto update of cached image when base image is updated

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#158]
https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1356932#post1356932
states this is done automatically.

I cannot demonstrate this to be true and cannot find the code that does this check....I have always had to delete the cached image.
I modified the cached image date to yesterday and modified the base image....nothing changed.

**Comment by lat9** [comment]
Conditional corrected; thanks for the report!

**Comment by torvista** [comment]
confirmed corrected!

**Comment by lat9** [comment]
So I remember, I normally keep issues open until they're included in a release ... re-opening.
