### ISSUE TITLE
php 7.1 additional_images.php PHP Fatal error:  Uncaught Error: Cannot use string offset as an array

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#16]
line 74 is
`$list_box_contents = '';`
This was changed in ZC155e to
`$list_box_contents = array();`
Which cures the error of the title.

**Comment by lat9** [comment]
This will be "rectified" when support is dropped for Zen Cart versions prior to 1.5.5 (see #21), since the IH4/5 plugin will no longer distribute that file.
