### ISSUE TITLE
"Force canvas" setting doesn't apply

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#169]
... as reported in [this](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1359066#post1359066) support-thread posting.

**Comment by simon1066** [comment]
This new class file (bmz_image_handler.class.php) prevents the 'small images zoom on hover' from working. Image hover works when reverting to the v5.1.3 class file.

**Comment by lat9** [comment]
Ah, yes.  I was testing out some alternatives to that `imagehover.js` (see #139) and didn't put the original code 'back'.  Please note that that functionality will be removed from a future version of IH, due to its compatibility issues and general wonky behavior.

**Comment by simon1066** [comment]
I've been toying with whether to leave this turned on, due to its wonkiness. You've helped me decide!
