### ISSUE TITLE
"(unreleased)" in configuration_value description

### ISSUE THREAD

**Issue by drbyte** [DivaVocals/zen_Image-Handler#209]
While scanning the changes in #207 I noticed the following which appears to be an artifact that may make sense to remove:

<img width="953" alt="Pull Request #207 · DivaVocalszen_Image-Handler 2020-10-19 at 11 48 22 AM" src="https://user-images.githubusercontent.com/404472/96474859-41044c00-1201-11eb-8ab6-de0327ba607e.png">

**Comment by lat9** [comment]
I'm 'on the fence' on this, since v4.3.4 was never _officially_ released.

**Comment by drbyte** [comment]
Understood. 
Granted, that version number is ancient compared to current releases and IMO just creates unnecessary cognitive distraction for the end-user. 
It's your call of course. If it were me I'd remove all in-mod mentions of pre-v5.0.0 release numbers when someone has v5.x.x installed. Then remove all 5.x mentions when they have v6.x installed. Otherwise the end-user just goes wondering "what version do I have again? is this relevant to me? can I even use this feature?". They can consult the already-excellent docs for differences between versions or to read when a feature was added/changed.

Again: just offering an alternate perspective. Entirely your call!  If you decide to keep it as-is I won't be bothered :)

**Comment by lat9** [comment]
OK, I'm 'in'.
