### ISSUE TITLE
Remove use of $GLOBALS['value'] in deference to global $value (PHP 8.1 interoperation).

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#215]
PHP 8.1 will be disallowing `$GLOBALS['value']` modifications (the construct can still be used for read-only use).  See [this](https://stitcher.io/blog/new-in-php-81) blog-post for additional information.

**Comment by drbyte** [comment]
Clarification for those who read this issue: PHP 8.1 will be disallowing `$GLOBALS = []` and other mass-re-assignments.

Core Zen Cart code prefers to not use the `$GLOBALS['foo'] = whatever;` syntax unless truly necessary, favoring `global $foo; $foo=whatever;` syntax instead. That's what's driving these modifications.

**Comment by lat9** [comment]
Thanks, DrByte, for that clarification.
