### ISSUE TITLE
ZC158: Admin, Click to enlarge image popup broken 

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#219]
Tested on Zc158 vanilla.
The new window opens a shopfrontpage with no product details.

**Comment by lat9** [comment]
Was the associated product disabled?  The `popup_image` page will display "No image" if the product is disabled.

**Comment by drbyte** [comment]
What's the actual URL of the shopfrontpage in the popup? (Press CTRL+L in the browser if the Address Bar isn't visible)

Is it a DIR_FS_CATALOG or other define issue?

**Comment by torvista** [comment]
(php 8.0.1)

The Click to enlarge link is
javascript:popupWindow('https://www.dev.test/zencart-158/index.php?main_page=popup_image&pID=1')

![Clipboard01](https://user-images.githubusercontent.com/4391026/109051392-c5e50200-76da-11eb-866c-2eafabe6d8e9.gif)

Additional information...on my production (156) shop, I have added a popup on the shipping estimator page.
On the in-development ZC158 production shop, that popup and this one both have a similar result: a shopfront page, but in my case the page is incomplete like it has choked on something...but there are no debugs. I did not find the solution in the short time I looked at it. But it may imply that the issue here is not specific to IH, but some ZC158 change...I always suspect some sanitation aspect.

**Comment by drbyte** [comment]
That seems like something amuck with the site config (Apache/whatever). Why is main_page=popup_image showing the home page?  Maybe the directory is broken? Maybe the page (includes/modules/pages directory) isn't found?

**Comment by torvista** [comment]
It wasn't clear that the content is missing:

![Clipboard03](https://user-images.githubusercontent.com/4391026/109054010-a69ba400-76dd-11eb-99f1-4f96d501b607.gif)

**Comment by torvista** [comment]
I take it this works for everyone else?

**Comment by lat9** [comment]
I haven't (yet) tried on zc158.

**Comment by drbyte** [comment]
@torvista This appears to be a bug in ZC v158. I believe this fixes it: https://github.com/zencart/zencart/commit/7e73fcc4a9daab22a5a0787c4b279c7698bcf141

**Comment by torvista** [comment]
👏 
Glad to see there is some wheat in all my chaff.

**Comment by lat9** [comment]
> 
> 
> Was the associated product disabled? The `popup_image` page will display "No image" if the product is disabled.

Re-opened to deal with the above.  If the product is disabled, the popup image displays "No image available".  I'm thinking to not display that link when the product is disabled (with appropriate messaging).
