### ISSUE TITLE
admin, product view, concatenated paths / double slashes in url / so file not found error

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#220]
After removing the silence operators.
On each page refresh, this warning due to the concatenating of constants. 

> PHP Warning: getimagesize(D:/FullPathToShop/public_html/tienda-158//tienda-158/bmz_cache/ventureshield/generic_full_kitjpg.image.80x80.jpg): Failed to open stream: No such file or directory in D:\FullPathToShop\public_html\tienda-158\admin\image_handler.php on line 571.

In my PR'ed file this is
```
            case 'layout_info':
                [$width, $height] = getimagesize(DIR_FS_CATALOG . $selected_image_file);
                $heading[] = [
                    'text' => '<strong>' . TEXT_INFO_IMAGE_INFO . '</strong>'
                ];
```

As $selected_image_file traces back to the class....I'll step further back.

**Comment by lat9** [comment]
I'm having a hard time replicating this.  What action is being performed when the warning is logged?

**Comment by drbyte** [comment]
Given that the path is repeated, is it a DIR_WS_ZZZZZ or other define issue?

**Comment by lat9** [comment]
> 
> 
> I'm having a hard time replicating this. What action is being performed when the warning is logged?

Note to self:  It helps to make edits to the directory that you're testing on.

**Comment by lat9** [comment]
> 
> 
> Given that the path is repeated, is it a DIR_WS_ZZZZZ or other define issue?

I've replicated it now; it's the fact that the `$selected_image_file` is prepended with DIR_WS_CATALOG.
