### ISSUE TITLE
Changing bmz_cache filenames, effect on SEO?

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#25]
In reviewing [this ](https://github.com/DivaVocals/zen_Image-Handler/commit/45abaa8eddb2d81c1408f8803e886c015dc1c0a8)commit, it occurred to me that applying the bmz-cached filename change as an _update_ might have negative impacts on stores if the hashed versions of the filenames have been indexed by search engines ... so that those images have "link juice".

Perhaps we should use yet-another configuration setting to control whether/not the updated naming should take effect?

**Comment by lat9** [comment]
I've seen stores that have hard-coded links in their product/category descriptions to the cached images' names, so need to provide backward-compatibility to those stores!

**Comment by DivaVocals** [comment]
I implemented this change many years ago for my client. And saw on no negative impact. The real link juice was in his product and category links. The changing URLs for his images had a very miniscule impact on his site SEO scores and performance. And I did confere with his SEO marketing person before making this change. But that's just my $0.03.

**Comment by DivaVocals** [comment]
Call to pardon the bad grammar typing on a tiny device using talk-to-text technology it isn't always perfect.. 🤣🤣

**Comment by lat9** [comment]
Thanks, Diva!  I should probably change the title here, since the change has "morphed" based on seeing clients that have hard-coded image links to the `bmz_cache` versions.  Without the configuration switch to allow them to remain as-is, there would be busted links in those product definitions on an IH upgrade.
