### ISSUE TITLE
sorting and formatting of pulldowns...

### ISSUE THREAD

**Issue by proseLA** [DivaVocals/zen_Image-Handler#251]
https://github.com/DivaVocals/zen_Image-Handler/blob/d8965f5be4f77fbf3eeec2f5db38400f966e6ba9/1_Installation_Files%20(v1.5.5)/YOUR_ADMIN/image_handler.php#L287-L290

i am not sure what the preference is for the majority of IH users; but there has always been an ongoing push-pull with regards to the sorting of displayed products in the ZC repo.  for v157, the default sort is products_name; for v158 this has changed to products_model.  for my clients, it is far from ideal.  in v158, one can add the sort field to the pulldown to change according, ie:
```
zen_draw_pulldown_products('products_filter', 'size="5"', '', true, $products_filter, true, true, 'products_name')
```
in addition, for both pull downs i am also a fan of adding the form-control class to the parameters var. ie:
```
'size="5" class="form-control"'
```

**Comment by lat9** [comment]
Noting that the 'form-control' class was previously added for #256.
