### ISSUE TITLE
Correct IH logs when a product's image is a .webp type

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#265]
See [this](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1390946#post1390946) Zen Cart forum posting for additional details.

**Comment by lat9** [comment]
Note: Thanks to @brittainmark for doing the leg-work!

**Comment by brittainmark** [comment]
You are welcome. Mine was just a sticking plaster. Might be better to have a constant that holds the image types that are processed and do nothing on all other image types. More future proof.

**Comment by lat9** [comment]
@brittainmark, I'd appreciate a review since I'm having "difficulties" requesting that via the just-pushed PR.
