### ISSUE TITLE
Disable Image Hover on Smaller Touchscreen Devices

### ISSUE THREAD

**Issue by DivaVocals** [DivaVocals/zen_Image-Handler#4]
Use the mobile detect script to disable the image hover (if enabled) at specified (admin configurable) media breaks or on specific devices (smartphones and some of the smaller tablets). The reason for very specific logic is because the image hover is difficult if not near impossible to dismiss on smaller touchscreen devices (smartphones and some of the smaller tablets) while larger touchscreen devices will have no issues whatsoever with the image hover.. 

I think using a specific media break versus a device type or simply disabling the image hover function altogether on smartphone/tablet devices would ensure that only the smaller devices most negatively affected are targeted to give a better user experience on these smaller devices. This exclusion does NOT need to be applied to ALL tablets.

The change needs to be "smart" enough so that if the mobile detect script is NOT present, that no action is taken. OR perhaps the better way to do this is that the installer needs to be "smart" and if the mobile detect script is NOT in place to upload the file.

**Comment by lat9** [comment]
This is doable without configuration change.  The store can update the style_imagehover.css that is part of the `IH` distribution to hide the popup display using CSS!

Just determine the conditions under which the display should/should-not be displayed, using these styles:

`#trailimageid { display: none; }` ... to hide the display
`#trailimageid { display: block; }` ... to show the image-hover

I'll add a section to the readme describing how to do this.
