### ISSUE TITLE
$page has wrong value on image_handler.php

### ISSUE THREAD

**Issue by Zen4All** [DivaVocals/zen_Image-Handler#53]
I was looking through the code, and was wondering why i never see the search box on the right side of the page.
making a dump of $pagegave me the following array
```
Dump of an array: Array
(
    [name] => Media Types
    [file] => media_types
    [params] => 
)
```
This is obviously not the right value, as something like 'manager', or 'admin' was expected. It looks like $page is some global variable, so I changed it to $ih_page. Guess what  happened 😃 . The search box showed up.
I have not tested for other effects of changing the variable name, but otherwise i propose to make the change. If okay, I will/can make a PR.

**Comment by lat9** [comment]
Where did you make that change?  Did you change all occurrences of $page to $ih_page within /YOUR_ADMIN/image_handler.php and /YOUR_ADMIN/includes/ih_manager.php?

My initial take is that this change should be deferred to v5.0.1 (a bugfix release) just due to the potential testing required and the fact that it's not come up as an issue before!

**Comment by Zen4All** [comment]
Yes, I changed all instances, but it would indeed need some testing. I'll see what I can do tonight.

**Comment by Zen4All** [comment]
I found the problem.
At line 30 $page is set to the correct $_GET parameter.
then is used at line 51.
further below, the 'header.php' is loaded, which loads the 'header_navigation.php'.
Inside 'header_navigation.php' $page is used in a foreach loop, where the array values mentioned above are set. 
```
<?php foreach (zen_get_admin_menu_for_user() as $menuKey => $pages) { ?>
            <li class="dropdown">
              <a href="<?php echo zen_href_link(FILENAME_ALT_NAV) ?>" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><?php echo $menuTitles[$menuKey] ?><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($pages as $page) { ?>
                  <li><a href="<?php echo zen_href_link($page['file'], $page['params']) ?>"><?php echo $page['name'] ?></a></li>
                <?php } ?>
              </ul>
            </li>
          <?php } ?>
```
these values are then used on line 199 for the search box and on line 220 through 229 for the nav links.
On line 240 $page is correctly reset to the $_GET value.
This results in the bulk of the page working correctly, and is probably why nobody ever noticed the bug.

**Comment by lat9** [comment]
Nice detective work, @Zen4All ... are you going to generate a PR or shall I?

Either way, the `$_GET['page']` (and associated forms/links) should be changed to use (as you suggested) `$_GET['ih_page']` instead so that there's no data overlap.

**Comment by Zen4All** [comment]
I'll make a pr for that.
Also, what are we going to do with the search box? we can deletete it completetely, since nobody ever seem to have missed it.

**Comment by lat9** [comment]
What functionality is the search supposed to provide?  In my opinion, the feature has been masked for years and, without a driving need for the functionality the search should just be removed.

I'm, as always, open for opposing views!

**Comment by Zen4All** [comment]
The search function shows on multiple Zen Cart pages, like attributes controller. Supposedly it can be used to look up products, but you are redirected to the products listing.
Personally I have never used it.
