### ISSUE TITLE
update page layout

### ISSUE THREAD

**Issue by Zen4All** [DivaVocals/zen_Image-Handler#61]
@lat9 
How do you feel about updating the IH page to a more modern look?
My proposal is to make the page tabbed, with bootstrap.
![tabs](https://user-images.githubusercontent.com/2766593/31908259-8fb3254c-b836-11e7-8067-dc0e84ec8724.png)
Also making the page a bit more responsive. In the style of the configuration page.
![resp1](https://user-images.githubusercontent.com/2766593/31908581-afd10ba4-b837-11e7-9ed0-44a5076ab828.png)
![resp2](https://user-images.githubusercontent.com/2766593/31908584-b2aa6668-b837-11e7-81ff-a697bcb04c6b.png)
.

**Comment by lat9** [comment]
Sounds like a great idea, @Zen4All, but I don't want to hold up the 5.0.0 re-release for the additional coding and testing.

Why don't we target a 5.1.0 release?

**Comment by Zen4All** [comment]
Sounds like a plan 👍

**Comment by lat9** [comment]
I believe that this request has been fulfilled by the changes associated with #221.

**Comment by lat9** [comment]
... and now _seriously_ fulfilled by changes for #256; closing.
