### ISSUE TITLE
Tools->Image Handler:  What's the purpose of the Preview link?

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#68]
Within the main IH admin tool, there's a `Preview` link that appears to display a couple of fixed images ... for each of the gif, jpg and png image types.

As the title indicates, what's the purpose of that display?  Without a good reason for the inclusion, I'm inclined to remove that "feechur" in a subsequent IH release.

**Comment by Zen4All** [comment]
I never really looked in to it, but I always assumed that it was used to show which image sizes were generated. But if that is not the case, it can be removed.

**Comment by lat9** [comment]
Thanks for the response.  It's just displaying those fixed images ... nothing to do with any images uploaded by the admin.

**Comment by drbyte** [comment]
Ya, seems superfluous to me

**Comment by lat9** [comment]
The only reason that I can think of for keeping the functionality is that it appears to be a pseudo-verification of the IH-related settings.  I haven't taken a "deep dive" to validate that presumption, though.
