### ISSUE TITLE
jscript/jscript_imagehover.js causes rest of JS to load below footer

### ISSUE THREAD

**Issue by bislewl** [DivaVocals/zen_Image-Handler#7]
There is an issue with the jscript/jscript_imagehover.js that causes the </head>. Then the rest of the JS is loading outside of the <head>

**Comment by DivaVocals** [comment]
You issue report seems incomplete/unclear.. Can you clarify, and since I've not seen any other reports of issues, you will need to provide details on how to re-create what it is you are reporting..

Finally if you have the fix, would you be willing to share via a PR??

**Comment by bislewl** [comment]
I actually haven't looked at a fix. 
However it's fairly easy to reproduce.
1.) Examine the <head> on a zencart store notice all the CSS/JS is loading in the head
2.) Install IH
3.) Repeating step 1 Notice how now after the jscript_imagehover.js is loaded in the <head> everything after it is loaded in the body.

**Comment by DivaVocals** [comment]
This issue is only "seen" when one uses the browsers "Inspect Element" tool..

**Comment by bislewl** [comment]
I found the solution creating a Pull request now
