### ISSUE TITLE
Split into multiple menu items, to allow for profile permissions

### ISSUE THREAD

**Issue by drbyte** [DivaVocals/zen_Image-Handler#70]
I'm thinking that the main UI for IH should be under the Catalog menu, not Tools.

And that the Uninstall option should be someplace where its use can be limited on a per-admin-profile basis.

**Comment by lat9** [comment]
I'll buy the moving the IH UI under Catalog.  Note that the uninstall option (for 5.0.0) has already been culled to a separate script so that it's subject to per-admin-profile authorization.

**Comment by drbyte** [comment]
> Note that the uninstall option (for 5.0.0) has already been culled to a separate script so that it's subject to per-admin-profile authorization

Yes, but it's still in the UI:
<img width="471" alt="image 2017-12-14 at 2 08 23 pm" src="https://user-images.githubusercontent.com/404472/34009817-5806442e-e0d8-11e7-8b88-ab058826e9e1.png">

**Comment by lat9** [comment]
Yes, but (like Edit Orders) it's a separate module so requires separate admin authorization.

**Comment by Zen4All** [comment]
Maybe adding something like if used is superuser then show link?

**Comment by lat9** [comment]
@Zen4All, that sounds like a plan.  If the user's not authorized, the link won't show.

**Comment by Zen4All** [comment]
You want me to make a PR, or will you do it.

**Comment by lat9** [comment]
I've got it covered; thanks for the offer.

**Comment by Zen4All** [comment]
👍
