### ISSUE TITLE
Terms: "default" could be clarified

### ISSUE THREAD

**Issue by drbyte** [DivaVocals/zen_Image-Handler#71]
In the Readme instructions it talks about "MUST load a Default image", and then tries to explain what "default" means.

Wouldn't calling it "Original" be better? Esp if using IH to generate sized images.

And then elsewhere where "default" means "thumbnail", call it that.

And then explain that if med/large variants don't exist then the "thumbnail" is used as a fallback.

Or something along those lines. 

Might end up reducing the amount of words needed to explain the concepts.

**Comment by lat9** [comment]
I'll buy that, noting that the change will be needed to the admin-side language files for consistency.

**Comment by lat9** [comment]
Current thinking:

Base Image: The image that was uploaded, whether main or additional.  This image is used to create the small/medium/large images.

Small Image: The image created using the "small" image sizes (was "default").

Medium Image: The medium image created.

Large Image: The large image created.

The Base Image information will be added to a product's image-display list.

**Comment by DivaVocals** [comment]
Sounds good there was always some ambiguity about the terminology used. I had to do some deep digging to come up with the definitions to help explain to people what they were seeing and how things are happening and why..

**Comment by drbyte** [comment]
One thing that's admittedly always been confusing is the purpose of the "Medium" image, since it's only ever used as the Product Image on the Product Page. In the default core code anyway.

And this adds confusion to the IH display when there's a whole column for the Medium image, which leaves a gap for all the Additional Images added to a product. 

I guess there's validity in supporting medium images for Additionals ... to support something like a image-navigator which swaps out the product's main image for its additionals, but without zooming into a bigger lightbox with the Large image.

**Comment by lat9** [comment]
Additional changes provided by the most recent commit to #114.  Different "sidebar" forms are now used to distinguish "main" from "additional" image processing.  The 'medium' image is no longer either requested or created when an additional image is being created, edited or deleted.  Refer also to the markdown versions of the readme (currently on the v510 branch).
