### ISSUE TITLE
Modification to 'unhashed' cache-image storage.

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#72]
See [this ](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1339941#post1339941)Zen Cart posting for details.

**Comment by brittainmark** [comment]
An alternative to my original suggestion would be to introduce a new constant "IH_CACHE_NAMING_LENGTH" default it to 1. then change protected function getCacheName($data, $ext='') 
    {
        $md5  = (IH_CACHE_NAMING == 'Hashed') ? md5($data) : $data;
        $file = $GLOBALS['bmzConf']['cachedir'] . '/' . substr($md5, 0, 1) . '/' . $md5 . $ext;
--TO--
protected function getCacheName($data, $ext='') 
    {
        $md5  = (IH_CACHE_NAMING == 'Hashed') ? md5($data) : $data;
        $file = $GLOBALS['bmzConf']['cachedir'] . '/' . substr($md5, 0, IH_CACHE_NAMING_LENGTH) . '/' . $md5 . $ext;
---

Don't know what you think. Obviously you would have to add the constant and a check to ensure integer and may be have a max limit.

Don't know it that helps.

**Comment by torvista** [comment]
What does this code suggestion actually DO?

**Comment by drbyte** [comment]
On the surface I think it changes the cache subdir names from 1-char directory names to longer names ... in theory to spread things out so that while there may be "more" top-level subdirectories, the number of files inside each would be fewer because they're grouped on a longer "key".

eg: with 1-char
```
a/
  abcdefg1234
  abcdefg1235
  abcdefg1236
  ajklmno5555
  ajklmno5556
  ajklmno5557
b/
  bcdef987654
  bcdef987655
  bxcva3456
  bxcva3457
```
with 3-chars becomes
```
abc/
  abcdefg1234
  abcdefg1235
  abcdefg1236
ajk/
  ajklmno5555
  ajklmno5556
  ajklmno5557
bcd/
  bcdef987654
  bcdef987655
/bxc
  bxcva3456
  bxcva3457
```

**Comment by brittainmark** [comment]
Yes that is exactly what I was trying to do. I thought I had added a 
description to the mod.

My issue is that all my product names are a code that starts with the 
year as a 2 digit number so by only having one character 10 years worth 
of products go in to the same directory. As a consequence I still use 
the hash mechanism for all my images.

Not that up on git so sorry if i got it wrong.

Mark

**Comment by brittainmark** [comment]
This was added from support thread by lat9 [](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5)-Support-Thread&p=1339941#post1339941)
An alternative would be to reproduce the original directory structure where the files are located under bmz_cache. so
images/Crystals/20A/20A001.JPG goes in bmz_cache/Crystals/20A
That way the new files ate located in the same relative location to the original.

That is probably a lot more work and not necessarily back wards compatible.

As i said when I raised the suggestion If this not a way forward I will just keep on using the Hashed keys. It just means that house keeping take a bit longer when i get rid of products.

**Comment by torvista** [comment]
> That is probably a lot more work and not necessarily back wards compatible.

Still, seems a logical suggestion.

**Comment by brittainmark** [comment]
Think I have worked it out and its not that big a change.  
1) Create a new IH_CACHE_NAMING say "Mirrored"
2) modify init_image_handler.php lines 271-276 to add in the new cache naming type
`                $db->Execute(
                    "INSERT INTO " . TABLE_CONFIGURATION . " 
                        ( configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added, use_function, set_function ) 
                     VALUES 
                        ( 'Cache File-naming Convention', 'IH_CACHE_NAMING', '$default', 'Choose the method that <em>Image Handler</em> uses to name the resized images in the <code>bmz_cache</code> directory.<br /><br />The <em>Hashed</em> method was used by Image Handler versions prior to 4.3.4 and uses an &quot;MD5&quot; hash to produce the filenames.  It can be &quot;difficult&quot; to visually identify the original file using this method.  If you are upgrading Image Handler from a version prior to 4.3.4 <em>and</em> you have hard-coded links in product (or other) definitions to those images, <b>do not change</b> this setting from <em>Hashed</em>.<br /><br />Image Handler v4.3.4 (unreleased) introduced the concept of a <em>Readable</em> name for those resized images.  This is a good choice for new installations of <em>IH</em> or for upgraded installations that do not have hard-coded image links. <em>Mirrored</em> is the same as readable but it creates a directory structure under bmz_cache that mirrors the directory structure where the origional images are saved.', $cgi, 1006, now(), NULL, 'zen_cfg_select_option(array(\'Hashed\', \'Mirrored'\, \'Readable\'),')"
                );`
3) Modify bmz_image_handler.class.php protected function getCacheName replace lines 413-414 with 
` case 'Hashed':
// Hash the name and place in directory using first character of hashed string              
            $md5  = md5($data);
            $file = $GLOBALS['bmzConf']['cachedir'] . '/' . substr($md5, 0, 1) . '/' . $md5 . $ext;
            break;
          case 'Mirrored':
// Use readable file name and place in mirrored original directory
            $file = $GLOBALS['bmzConf']['cachedir'] . '/' . $data . $ext;
            break;
          default:
// Use readable file name and place directory using first character of name
            $file = $GLOBALS['bmzConf']['cachedir'] . '/' . substr($data, 0, 1) . '/' . $data . $ext;
            break;
        }`
4)  Modify bmz_image_handler.class.php public function get_resized_image replace lines 346-355 with 
` if (IH_CACHE_NAMING == 'Mirrored') {
                    $image_dirname = ($image_path['dirname']);
                    if ($image_dirname == rtrim(DIR_WS_IMAGES, '/')) {
                      $image_dir = '';
                    } else {
                      $image_dir = substr($image_path['dirname'],strlen(DIR_WS_IMAGES)) . '/';
                    }
                } else {
                
                  // get last directory from path and clean that up just like the image's base name
                  $image_dirname = $this->sanitizeImageNames(basename($image_path['dirname']));
                
                  // if last directory is images (meaning image is stored in main images folder), do nothing, else append directory name
                  if ($image_dirname == rtrim(DIR_WS_IMAGES, '/')) {
                      $image_dir = '';
                  } else {
                      $image_dir = $image_dirname . '-';
                  }
                }`

Not sure what needs doing about upgrade and docs.
I am happy to fork and create a pull request it that makes it easier to verify my suggestion.

**Comment by brittainmark** [comment]
Have created Pull request 207 for Mirrored option.
