### ISSUE TITLE
admin tools menu causes debug error

### ISSUE THREAD

**Issue by torvista** [DivaVocals/zen_Image-Handler#75]
The admin tools menu item causes a debug error/is broken as is missing a parameter:

`if (check_page(FILENAME_IMAGE_HANDLER_UNINSTALL)) {`

Also I note that for upgrade/install file-comparison purposes, modules /template/additional_images.php and main_product_image.php when comparing to ZC155f:
a) lots of original blocks are indented differently although they are the same code, making comparison to a third override file more complicated.
b) there are some minor plugin-unrelated differences to the original file: use of count instead of sizeof.

**Comment by lat9** [comment]
Thanks, @torvista!  I would have stumbled upon that eventually!  I'll get that debug-log fixed.

You've also discovered that I'm going through and "re-factoring" these files.  I know it makes it "difficult" to to the 3-way difference, but it's needed (especially the indentation) for me to understand (and correct in cases) the HTML/PHP interactions.  The count vs. sizeof changes are part of that re-factoring, using the count function when determining array "sizes".
