### ISSUE TITLE
Add "View configuration" admin-menu item

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#83]
Add a "View configuration" item to the IH-5 admin menu, displaying the information being used from the $ihConf settings as well as the various `Configuration->Images` values.  That page will also display any issues (like out-of-range `quality` or `background` settings) detected.

**Comment by Zen4All** [comment]
Like the idea. Will it also be possible to edit the values?

**Comment by lat9** [comment]
For the values in the configuration, yes.  For the values in the $ihConf array (currently present in storefront /extra_configures files) , no -- due to file-locking concerns.

**Comment by lat9** [comment]
That's the plan, @drbyte!
