### ISSUE TITLE
Medium/Large: Will find/use alternate image extensions if primary is not found

### ISSUE THREAD

**Issue by lat9** [DivaVocals/zen_Image-Handler#88]
If a product's image name is, for instance,` myimage.jpg` and its medium image `/medium/myimage_MED.jpg` **_is not_** found but does exist as an alternate file-type (e.g. `/medium/myimage_MED.gif`), the processing will currently use that alternate file-type for the display.

**Comment by drbyte** [comment]
Does that "have to be" considered a bug?

**Comment by lat9** [comment]
Well, given that I lost a good 4 hours yesterday trying to figure out why a **_different_** medium image was being displayed ...

The `ihConf` configuration indicated `no_change` for the file extension for the medium/large images, but the file-extension was changed anyway!
