### ISSUE TITLE
"Clear image cache" link not working in Admin Area

### ISSUE THREAD

**Issue by jazzman346** [DivaVocals/zen_Image-Handler#9]
I've spent some time figuring this one out. Pretty easy fix after all.

It appears that the link doesn't work when a folder "0" gets created in the bmz_cache folder. "0" will be interpreted as "false" and break the loop, hence not cleaning anything.

Please change line 25 in /YOUR_ADMIN/includes/functions/extra_functions/functions_bmz_io.php 
from -> while ($file = $dir->read()) {
to -> while (false !== ($file = $dir->read())) {

Regards,
Jazzman346

**Comment by DivaVocals** [comment]
Thanks for this.. will make the change.. You can always submit a pull request when you find these kinds of fixes going forward.. :)

**Comment by jazzman346** [comment]
Solve by merging pull request #10. Thanks!
